// ★ Demo 花名册 — Leading-花名册（2026-6-AI专用）
window.__DATA_VERSION__ = 'demo-20260715-v6';
var __PRELOADED_EMPLOYEES__ = [
  {
    "empId": "LD001",
    "name": "张玉基",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "总经理",
    "joinDate": "2021-03-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD002",
    "name": "顾佳",
    "status": "已转正",
    "center": "采购中心",
    "dept": "采购中心",
    "position": "经理",
    "joinDate": "2017-09-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD003",
    "name": "仲子进",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "销售总监",
    "joinDate": "2018-03-20",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD004",
    "name": "王鹏",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发副总",
    "joinDate": "2019-10-14",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD005",
    "name": "唐爱珍",
    "status": "已转正",
    "center": "采购中心",
    "dept": "采购中心",
    "position": "仓储主管",
    "joinDate": "2020-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD006",
    "name": "范文越",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2020-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD007",
    "name": "施慧娟",
    "status": "已转正",
    "center": "财务中心",
    "dept": "财务中心",
    "position": "财务经理",
    "joinDate": "2021-05-10",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD008",
    "name": "李敏",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "生产专员",
    "joinDate": "2021-06-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD009",
    "name": "邵强",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "销售工程师",
    "joinDate": "2021-06-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD010",
    "name": "蔡亚珍",
    "status": "已转正",
    "center": "人力资源行政中心",
    "dept": "人力资源行政中心",
    "position": "人力行政经理",
    "joinDate": "2021-07-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD011",
    "name": "孙依暄",
    "status": "已转正",
    "center": "采购中心",
    "dept": "采购中心",
    "position": "采购助理",
    "joinDate": "2021-08-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD012",
    "name": "薛金鑫",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "生产专员",
    "joinDate": "2021-09-13",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD013",
    "name": "杨烨",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "计划专员",
    "joinDate": "2021-11-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD014",
    "name": "张梦",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "销售工程师",
    "joinDate": "2022-03-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD015",
    "name": "邵超凤",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "生产专员",
    "joinDate": "2022-06-27",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD016",
    "name": "贺陆青青",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "资深研究员",
    "joinDate": "2022-07-11",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD017",
    "name": "吴云萍",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2022-08-02",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD018",
    "name": "袁月贤",
    "status": "已转正",
    "center": "财务中心",
    "dept": "财务中心",
    "position": "会计",
    "joinDate": "2022-08-10",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD019",
    "name": "卓浩",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2022-08-16",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD020",
    "name": "洪霞",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发主管",
    "joinDate": "2022-08-25",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD021",
    "name": "华晨",
    "status": "已转正",
    "center": "CDMO中心",
    "dept": "CDMO中心",
    "position": "注册经理",
    "joinDate": "2022-08-29",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD022",
    "name": "夏羽",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "海外销售经理",
    "joinDate": "2022-09-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD023",
    "name": "张玉印",
    "status": "已转正",
    "center": "采购中心",
    "dept": "采购中心",
    "position": "设备工程师",
    "joinDate": "2022-10-08",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD024",
    "name": "陈贝贝",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2022-11-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD025",
    "name": "张迁",
    "status": "已转正",
    "center": "CDMO中心",
    "dept": "CDMO中心",
    "position": "注册工程师",
    "joinDate": "2022-11-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD026",
    "name": "赵洁岚",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "生产主管",
    "joinDate": "2023-02-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD027",
    "name": "潘晓惠",
    "status": "已转正",
    "center": "财务中心",
    "dept": "财务中心",
    "position": "出纳",
    "joinDate": "2023-02-15",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD028",
    "name": "王博",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "销售副总",
    "joinDate": "2023-02-21",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD029",
    "name": "王艳玲",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "资深研发工程师",
    "joinDate": "2023-03-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD030",
    "name": "薛延",
    "status": "已转正",
    "center": "质量中心",
    "dept": "质量中心",
    "position": "QA工程师",
    "joinDate": "2023-03-24",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD031",
    "name": "朱小凤",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "产品经理",
    "joinDate": "2023-04-18",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD032",
    "name": "许来利",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2023-05-04",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD033",
    "name": "周玲",
    "status": "已转正",
    "center": "质量中心",
    "dept": "质量中心",
    "position": "QC工程师",
    "joinDate": "2024-03-05",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD034",
    "name": "梅可栋",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "采购主管",
    "joinDate": "2024-04-10",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD035",
    "name": "许浩",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发助理工程师",
    "joinDate": "2024-04-18",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD036",
    "name": "范冬冬",
    "status": "已转正",
    "center": "生产中心",
    "dept": "生产中心",
    "position": "配液专员",
    "joinDate": "2025-05-06",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD037",
    "name": "毕泳",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发助理工程师",
    "joinDate": "2025-06-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD038",
    "name": "张玮",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "病毒质控品销售",
    "joinDate": "2025-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD039",
    "name": "李梦楠",
    "status": "已转正",
    "center": "营销中心",
    "dept": "营销中心",
    "position": "产品经理",
    "joinDate": "2025-07-01",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD040",
    "name": "李华中",
    "status": "已转正",
    "center": "研发中心",
    "dept": "研发中心",
    "position": "研发工程师",
    "joinDate": "2025-11-03",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD041",
    "name": "王梅君",
    "status": "已转正",
    "center": "人力资源行政中心",
    "dept": "人力资源行政中心",
    "position": "人事经理",
    "joinDate": "2026-03-23",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  },
  {
    "empId": "LD042",
    "name": "徐德聚",
    "status": "已转正",
    "center": "总经办",
    "dept": "总经办",
    "position": "总助",
    "joinDate": "2026-05-07",
    "gender": "",
    "birthday": "",
    "phone": "",
    "email": "",
    "education": "",
    "resignDate": null
  }
];
